// *** Installs item-related spell: Fire Storm ***

WITH_SCOPE BEGIN
  // installing projectile
  ADD_PROJECTILE ~%MOD_FOLDER%/items/projectiles/a7_i1e9.pro~

  COPY ~%MOD_FOLDER%/items/projectiles/a7_i1e9x.vvc~ ~override~
       ~%MOD_FOLDER%/items/projectiles/a7_i1e9x.bam~ ~override~
       ~%MOD_FOLDER%/items/projectiles/a7_i1e9a.wav~ ~override~

  COPY ~%MOD_FOLDER%/items/a7_i1e9.spl~ ~override~
    SAY NAME1 @21130  // Fire Storm
    SET strref = RESOLVE_STR_REF(~Spell #9 triggered...~)
    READ_LONG 0x64 ofsAbil
    READ_SHORT 0x68 numAbil
    FOR (idx = 0; idx < numAbil; ++idx) BEGIN
      SET ofs = ofsAbil + (idx * 0x28)
      WRITE_SHORT (ofs + 0x26) a7_i1e9
    END

  COPY ~%MOD_FOLDER%/items/a7_isp9b.bam~ ~override~
END
