// *** Installs item-related spell: Mudslide ***

WITH_SCOPE BEGIN
  ADD_PROJECTILE ~%MOD_FOLDER%/items/projectiles/a7_i1e6.pro~

  COPY ~%MOD_FOLDER%/items/projectiles/a7_i1e6a.vvc~ ~override~
       ~%MOD_FOLDER%/items/projectiles/a7_i1e6a.wav~ ~override~
       ~%MOD_FOLDER%/items/projectiles/a7_i1e6s.bam~ ~override~
       ~%MOD_FOLDER%/items/projectiles/a7_i1e6t.bam~ ~override~

  COPY ~%MOD_FOLDER%/items/a7_i1e6.spl~ ~override~
    SAY NAME1 @21140  // Mudslide
    READ_LONG 0x64 ofsAbil
    READ_SHORT 0x68 numAbil
    FOR (idx = 0; idx < numAbil; ++idx) BEGIN
      SET ofs = ofsAbil + (idx * 0x28)
      WRITE_SHORT (ofs + 0x26) a7_i1e6
    END

  COPY ~%MOD_FOLDER%/items/a7_isp6b.bam~ ~override~
END
