// *** Item set for Chaos Sorcerers ***

// Effect spells
INCLUDE ~%MOD_FOLDER%/lib/items/spells_status.tpa~
OUTER_FOR (idx = 1; idx < 16; ++idx) BEGIN
  INCLUDE ~%MOD_FOLDER%/lib/items/spell_%idx%.tpa~
END


// Items
OUTER_SET kit_id = IDS_OF_SYMBOL(~kit~ ~A7_CHAOS_SORCERER~)
OUTER_SET kit_strref = RESOLVE_STR_REF(@1001)
OUTER_SET ability_strref = RESOLVE_STR_REF(@21000)  // Primeval Outburst

COPY ~%MOD_FOLDER%/items/a7_ipri.bam~ ~override~

INCLUDE ~%MOD_FOLDER%/lib/items/item_1.tpa~
INCLUDE ~%MOD_FOLDER%/lib/items/item_2.tpa~
INCLUDE ~%MOD_FOLDER%/lib/items/item_3.tpa~
INCLUDE ~%MOD_FOLDER%/lib/items/item_4.tpa~


// Finalizing tooltip.2da
COPY_EXISTING ~tooltip.2da~ ~override~
  LPF a7_fill_2da_cols END
BUT_ONLY


// BG1->SoD item import
ACTION_IF (GAME_IS ~eet~ || GAME_INCLUDES ~sod~) BEGIN
  EXTEND_TOP ~bd0120.bcs~ ~%MOD_FOLDER%/scripts/bd0120_top.baf~
  EXTEND_TOP ~bd0130.bcs~ ~%MOD_FOLDER%/scripts/bd0130_top.baf~
END

// BG1->BG2 item import
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
  EXTEND_TOP ~ar0602.bcs~ ~%MOD_FOLDER%/scripts/ar0602_top.baf~
  EXTEND_TOP ~ar0603.bcs~ ~%MOD_FOLDER%/scripts/ar0603_top.baf~
END
